apiVersion: litellm.bitkaio.com/v1alpha1
kind: LiteLLMVirtualKey
metadata:
  labels:
    app.kubernetes.io/name: litellm-operator
    app.kubernetes.io/managed-by: kustomize
  name: engineering-ci-key
spec:
  instanceRef:
    name: litellminstance-sample
  keyAlias: engineering-ci-key
  teamRef:
    name: engineering
  models:
    - gpt-4o
  maxBudget: "100"
  budgetDuration: "30d"
  rpmLimit: 60
  keySecretName: engineering-ci-api-key
