apiVersion: v2
name: litellm-operator
description: Kubernetes operator for deploying and managing production-ready LiteLLM AI Gateway instances
type: application
version: 0.6.0
appVersion: "0.6.0"
kubeVersion: ">= 1.28.0-0"
home: https://github.com/PalenaAI/litellm-operator
sources:
  - https://github.com/PalenaAI/litellm-operator
maintainers:
  - name: bitkaio LLC
    url: https://palena.ai
keywords:
  - litellm
  - ai
  - llm
  - gateway
  - proxy
  - kubernetes
  - operator
